[de]
contentDir = "content/deutsch"
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
languageName = "De"
title = "Bigspring Hugo"
weight = 2
[en]
contentDir = "content/english"
copyright = "© 2020-2021 depthfirst.in. All rights reserved. "
footer_content = "We are committed to partner with you. Help us understand your requirements and we deliver a clear plan of action and technical roadmap for you."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "En"
title = "Depth First"
weight = 1
