[en]
contentDir = "content/english"
copyright = "© 2020-2021 depthfirst.in. All rights reserved. "
footer_content = "We are committed to partner with you. Help us understand your requirements and we deliver a clear plan of action and technical roadmap for you."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "En"
title = "Depth First"
weight = 1
