[[footer_left]]
name = "About Us"
url = "#"
[[footer_left]]
name = "Contact Us"
url = "contact"
[[footer_middle]]
name = "Services"
url = "service"
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"
[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "How We Help"
url = "service"
weight = 2
[[main]]
name = "Insights"
url = "blog"
weight = 3
[[main]]
name = "FAQ"
url = "faq"
weight = 4
