author = "Themefisher"
contact_form_action = "#hs-chat-open"
description = "Digital Product Partner"
logo = "images/df-logo-indigo.png"
logo_width = "160px"
[navigation_button]
enable = true
label = "Chat With Us"
link = "#hs-chat-open"
[preloader]
enable = true
preloader = "/preloader.svg"
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/depthfirstai"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/depthfirstai"
title = "twitter"
[[social]]
icon = "fab fa-whatsapp"
link = "https://wa.me/919811282747"
title = "whatsapp"
[[social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/company/depthfirstai"
title = "linkedin"
