author = "Themefisher"
contact_form_action = "#hs-chat-open"
description = "Digital Product Partner"
logo = "images/df-logo-indigo.png"
logo_width = "160px"
[navigation_button]
enable = true
label = "Chat With Us"
link = "#hs-chat-open"
[preloader]
enable = true
preloader = "Depth First will attend you in a moment..."
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "fab fa-skype"
link = "#"
title = "skype"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
